name: deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Debug DockerHub Username
      run: echo "Docker Hub Username:${{ secrets.DOCKERHUB_USERNAME }}"
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .  # Verifica que el contexto sea el correcto
        file: ./Dockerfile  # Asegúrate de que la ruta al Dockerfile sea correcta
        push: true  # Subir la imagen al repositorio de Docker Hub
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nest-demo:latest  # Formato correcto para el tag

    


